# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cantango_editor"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["stanislaw"]
  s.date = "2011-11-04"
  s.description = "Admin Web UI to manage permissions - Who can do What on Which objects"
  s.email = "s.pankevich@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/cantango_editor/+.png",
    "app/assets/images/cantango_editor/-.png",
    "app/assets/images/cantango_editor/.gitkeep",
    "app/assets/images/cantango_editor/bg-1.gif",
    "app/assets/images/cantango_editor/bg-2.gif",
    "app/assets/images/cantango_editor/bg-model.png",
    "app/assets/images/cantango_editor/bg.gif",
    "app/assets/images/cantango_editor/bg_action.gif",
    "app/assets/images/cantango_editor/bg_action.png",
    "app/assets/images/cantango_editor/bg_can.gif",
    "app/assets/images/cantango_editor/bg_can.png",
    "app/assets/images/cantango_editor/bg_cannot.gif",
    "app/assets/images/cantango_editor/bg_cannot.png",
    "app/assets/images/cantango_editor/button-top-r.png",
    "app/assets/images/cantango_editor/button-top.png",
    "app/assets/images/cantango_editor/cantangologo.png",
    "app/assets/images/cantango_editor/cantangologo_big.png",
    "app/assets/images/cantango_editor/cantangologo_big2.png",
    "app/assets/images/cantango_editor/cantangologo_big3.png",
    "app/assets/images/cantango_editor/ico-uc.png",
    "app/assets/images/cantango_editor/images/ui-bg_diagonal-maze_20_6e4f1c_10x10.png",
    "app/assets/images/cantango_editor/images/ui-bg_diagonal-maze_40_000000_10x10.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_10_eceadf_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_10_f8f7f6_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_15_eceadf_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_15_f7f3de_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_15_ffffff_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_65_654b24_60x60.png",
    "app/assets/images/cantango_editor/images/ui-bg_fine-grain_68_b83400_60x60.png",
    "app/assets/images/cantango_editor/images/ui-icons_222222_256x240.png",
    "app/assets/images/cantango_editor/images/ui-icons_3572ac_256x240.png",
    "app/assets/images/cantango_editor/images/ui-icons_8c291d_256x240.png",
    "app/assets/images/cantango_editor/images/ui-icons_b83400_256x240.png",
    "app/assets/images/cantango_editor/images/ui-icons_fbdb93_256x240.png",
    "app/assets/images/cantango_editor/images/ui-icons_ffffff_256x240.png",
    "app/assets/images/cantango_editor/line2.png",
    "app/assets/images/cantango_editor/line3.png",
    "app/assets/images/cantango_editor/panel-l.gif",
    "app/assets/images/cantango_editor/panel-l.png",
    "app/assets/images/cantango_editor/panel-r.gif",
    "app/assets/images/cantango_editor/panel-r.png",
    "app/assets/images/cantango_editor/panel.gif",
    "app/assets/images/cantango_editor/panel.png",
    "app/assets/images/cantango_editor/remember.png",
    "app/assets/images/cantango_editor/sexy.png",
    "app/assets/images/cantango_editor/x.png",
    "app/assets/images/cantango_editor/xx.png",
    "app/assets/javascripts/cantango_editor/application.js",
    "app/assets/javascripts/cantango_editor/jquery.collapse.js",
    "app/assets/javascripts/cantango_editor/jquery.cookie.js",
    "app/assets/javascripts/cantango_editor/jquery.ui/jquery-ui-1.8.16.custom.js",
    "app/assets/javascripts/cantango_editor/jquery.ui/jquery.ui.selectmenu.js",
    "app/assets/stylesheets/cantango_editor/.main.css",
    "app/assets/stylesheets/cantango_editor/application.css",
    "app/assets/stylesheets/cantango_editor/areset.css",
    "app/assets/stylesheets/cantango_editor/clearing.css",
    "app/assets/stylesheets/cantango_editor/jquery-ui-1.8.16.custom.css",
    "app/assets/stylesheets/cantango_editor/jquery.ui.selectmenu.css",
    "app/assets/stylesheets/cantango_editor/main.css",
    "app/assets/stylesheets/cantango_editor/text.css",
    "app/controllers/cantango_editor/application_controller.rb",
    "app/controllers/cantango_editor/permissions_controller.rb",
    "app/helpers/cantango_editor/application_helper.rb",
    "app/models/cantango_editor/categories.rb",
    "app/models/cantango_editor/category.rb",
    "app/models/cantango_editor/permissions.rb",
    "app/views/cantango_editor/permissions/_footer.html.erb",
    "app/views/cantango_editor/permissions/_header.html.erb",
    "app/views/cantango_editor/permissions/_menu.html.erb",
    "app/views/cantango_editor/permissions/_new_categories_select.html.erb",
    "app/views/cantango_editor/permissions/_new_custom_targets.html.erb",
    "app/views/cantango_editor/permissions/_new_targets_select.html.erb",
    "app/views/cantango_editor/permissions/_permissions_form.html.erb",
    "app/views/cantango_editor/permissions/index.html.erb",
    "app/views/cantango_editor/permissions/index.js.erb",
    "app/views/cantango_editor/permissions/new_category.js.erb",
    "app/views/cantango_editor/permissions/new_custom_target.js.erb",
    "app/views/cantango_editor/permissions/new_target.js.erb",
    "app/views/cantango_editor/permissions/notes.html.erb",
    "app/views/cantango_editor/permissions/preview_raw.html.erb",
    "app/views/cantango_editor/permissions/temp _permissions_form.html.erb",
    "app/views/layouts/cantango_editor/application.html.erb",
    "cantango_editor.gemspec",
    "config/routes.rb",
    "lib/array.rb",
    "lib/cantango_editor.rb",
    "lib/cantango_editor/configuration.rb",
    "lib/cantango_editor/engine.rb",
    "lib/cantango_editor/version.rb",
    "lib/permissions_hash.rb",
    "lib/tasks/cantango-editor_tasks.rake",
    "lib/time_precise.rb",
    "script/rails",
    "spec/cantango_editor/configuration/configuration_spec.rb",
    "spec/cantango_editor/models/permissions_spec.rb",
    "spec/cantango_editor_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/javascripts/main.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/main_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/main_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/models/admin.rb",
    "spec/dummy/app/models/article.rb",
    "spec/dummy/app/models/comment.rb",
    "spec/dummy/app/models/concerto.rb",
    "spec/dummy/app/models/guest.rb",
    "spec/dummy/app/models/improvisation.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/song.rb",
    "spec/dummy/app/models/tune.rb",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/main/index.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/categories.yml",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/cantango.rb",
    "spec/dummy/config/initializers/cantango_editor.rb",
    "spec/dummy/config/initializers/devise.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/devise.en.yml",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/permissions.yml.save",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/development.sqlite3",
    "spec/dummy/db/migrate/20111018203622_create_posts.rb",
    "spec/dummy/db/migrate/20111018203648_create_articles.rb",
    "spec/dummy/db/migrate/20111018203800_create_comments.rb",
    "spec/dummy/db/migrate/20111018203817_create_songs.rb",
    "spec/dummy/db/migrate/20111018203827_create_tunes.rb",
    "spec/dummy/db/migrate/20111018203859_create_concertos.rb",
    "spec/dummy/db/migrate/20111018203917_create_improvisations.rb",
    "spec/dummy/db/migrate/20111019122217_devise_create_users.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/test.sqlite3",
    "spec/dummy/lib/assets/.gitkeep",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/script/rails",
    "spec/integration/navigation_spec.rb",
    "spec/permissions_hash_spec.rb",
    "spec/requests/requests_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/stanislaw/cantango_editor"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Rails Engine to manage permissions stored in yaml file"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cantango_editor>, [">= 0"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0"])
      s.add_runtime_dependency(%q<sweetloader>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<cantango>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<cutter>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<cantango>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<cutter>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<cantango>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<cutter>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<unicorn>, [">= 0"])
    else
      s.add_dependency(%q<cantango_editor>, [">= 0"])
      s.add_dependency(%q<sugar-high>, [">= 0"])
      s.add_dependency(%q<sweetloader>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<cantango>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<cutter>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<cantango>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<cutter>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<cantango>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<cutter>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
    end
  else
    s.add_dependency(%q<cantango_editor>, [">= 0"])
    s.add_dependency(%q<sugar-high>, [">= 0"])
    s.add_dependency(%q<sweetloader>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<cantango>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<cutter>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<cantango>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<cutter>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<cantango>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<cutter>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
  end
end

